import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import {createServer} from 'node:net';
import {resolve} from 'node:path';
let server:ChildProcess;
let url:string;
test.beforeEach(async()=>{
  const socket=createServer();await new Promise<void>(ok=>socket.listen(0,'127.0.0.1',ok));
  const port=(socket.address() as {port:number}).port;await new Promise<void>(ok=>socket.close(()=>ok()));
  url=`http://127.0.0.1:${port}`;
  server=spawn(resolve('../.build/signaling-test.exe'),['-listen',`127.0.0.1:${port}`,'-data',resolve(`../.build/admin-web-${Date.now()}`)],{stdio:'ignore'});
  await expect.poll(async()=>{try{return (await fetch(url+'/admin/')).status}catch{return 0}}).toBe(200);
});
test.afterEach(()=>server?.kill());

test('separate web admin authenticates, shows rooms and changes password',async({page,request})=>{
  await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).copiedParty=text}}});});
  const secret='test-secret-device-00000000000000000000';
  let response=await request.post(url+'/v2/rooms',{data:{op:'create',secret,name:'Север'}});
  const room=(await response.json()).room;
  response=await request.post(url+'/v2/rooms',{data:{op:'join',secret,room:room.id,name:'Лена'}});
  const host=(await response.json()).room.members[0].id;
  await request.post(url+'/v2/rooms',{data:{op:'list',secret,parties:[{id:'party-1',room:room.id,host,stage:'finished',revision:1,round:3,startedAt:1700000000,finishedAt:1700000200,players:[{id:host,name:'Лена',bot:false},{id:'other-device',name:'Игорь',bot:false},{id:'',name:'Bot secret',bot:true}]}]}});
  response=await request.post(url+'/v2/rooms',{data:{op:'admin-delete-room',secret,room:room.id}});
  expect(response.status()).toBe(403);
  await page.goto(url+'/admin/');
  await expect(page.locator('#admin-login-form')).toBeVisible();
  await page.getByLabel('Пароль администратора').fill('wrong');
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.locator('#auth-status')).toContainText('Неверный пароль');
  await page.getByLabel('Пароль администратора').fill('admin');
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.locator('.admin-room')).toHaveCount(1);
  await expect(page.locator('.admin-table thead th')).toHaveText(['Комната','Игроки (без ботов)','Партии']);
  await expect(page.locator('.admin-party')).toContainText('Игроки: Лена · Игорь');
  await expect(page.locator('.admin-party')).not.toContainText('Bot secret');
  await page.locator('[data-admin-toggle]').click();
  await expect(page.locator('.admin-party')).toBeHidden();
  await page.locator('#admin-refresh').click();
  await expect(page.locator('[data-admin-toggle]')).toHaveAttribute('aria-expanded','false');
  await page.locator('[data-admin-toggle]').click();
  await page.locator('[data-admin-copy]').click();
  const copied=await page.evaluate(()=>(window as any).copiedParty);
  expect(copied).toContain('Комната: Север');
  expect(copied).toContain('Партия: party-1');
  expect(copied).toContain('Игорь (other-device)');
  expect(copied).not.toContain('Bot secret');
  await page.screenshot({path:'../.build/admin-web.png'});
  await page.getByLabel('Текущий пароль').fill('admin');
  await page.getByLabel('Новый пароль',{exact:true}).fill('test-new-password');
  await page.getByLabel('Повторите новый пароль').fill('test-new-password');
  await page.getByRole('button',{name:'Сменить пароль',exact:true}).click();
  await expect(page.locator('#admin-login-form')).toBeVisible();
  await expect(page.locator('#auth-status')).toContainText('Пароль изменён');
  await page.getByLabel('Пароль администратора').fill('admin');
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.locator('#auth-status')).toContainText('Неверный пароль');
  await page.getByLabel('Пароль администратора').fill('test-new-password');
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.locator('.admin-room')).toHaveCount(1);
  await page.locator('[data-admin-delete="party"]').click();
  await page.locator('.app-confirm').getByRole('button',{name:'Удалить',exact:true}).click();
  await expect(page.locator('.admin-party')).toHaveCount(0);
  await page.getByRole('button',{name:'Выйти',exact:true}).click();
  await expect(page.locator('#admin-login-form')).toBeVisible();
});
